### ISSUE TITLE
Enregistrer un livre dans la bdd: POST /AjouterLivre

### ISSUE THREAD

**Issue by ggence** [ggence/lbbe-books#3]
Lors d'une requête **POST /AjouterLivre**  l'application doit appeler l'API de la BDD avec les bons paramètres contenue dans le corps de la requête POST.
ATTENTION: Lorsque la requête a eu lieu il faut prévenir l'utilisateur et lui rendre un page HTML qui indique que l’opération s'est bien passé (ou non).

**Comment by ggence** [comment]
Tu peux faire un ["new pull request" ](https://github.com/ggence/lbbe-books/tree/postAjouterLivre), ça me permet d'avoir des outils de gestions pour dire ce qui va ou pas :)
A lundi !

**Comment by ggence** [comment]
C'est bon :+1:

**Comment by HelPhil** [comment]
cool 😃


________________________________
De : ggence <notifications@github.com>
Envoyé : lundi 25 septembre 2017 08:43
À : ggence/lbbe-books
Cc : HelPhil; Assign
Objet : Re: [ggence/lbbe-books] Enregistrer un livre dans la bdd: POST /AjouterLivre (#3)


C'est bon 👍
